---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Update interface IP (Cisco)
  hosts: "{{ device }}"
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
  tasks:
    - name: Debug Netbox data structure (Cisco)
      debug:
        msg: "{{ data }}" 
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^cisco-2$")

    - name: Debug Netbox relevant variables (Cisco)
      debug:
        msg: "{{ device }}, {{ interface }}, {{ ip_address }}, {{ address_family }}, {{ description }}, {{ event }}, {{ timestamp }}, {{ data }}" 
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^cisco-2$")

    - name: Update IPv4 to l3 interface on {{ device }} (Cisco)
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv4:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      #when: address_family == '4' and hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: address_family == '4' and hostvars[inventory_hostname].tags.Name is match("^cisco-2$")

    - name: Update IPv6 to l3 interface on {{ device }} (Cisco)
      cisco.ios.ios_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv6:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      #when: address_family == '6' and hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: address_family == '6' and hostvars[inventory_hostname].tags.Name is match("^cisco-2$")

    - name: Update description to interface on {{ device }} (Cisco)
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          description: "{{ description }}"
      become: true
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^cisco-2$")

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
      become: true
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^cisco-2$")


- name: Update interface IP (Juniper)
  hosts: "{{ device }}"
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: Debug Netbox data structure (Juniper)
      debug:
        msg: "{{ data }}" 
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^juniper-2$")

    - name: Debug Netbox relevant variables (Juniper)
      debug:
        msg: "{{ device }}, {{ interface }}, {{ ip_address }}, {{ address_family }}, {{ description }}, {{ event }}, {{ timestamp }}, {{ data }}" 
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^juniper-2$")

    - name: Update IPv4 to l3 interface on {{ device }} (Juniper)
      junipernetworks.junos.junos_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv4:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      #when: address_family == '4' and hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: address_family == '4' and hostvars[inventory_hostname].tags.Name is match("^juniper-2$")

    - name: Update IPv6 to l3 interface on {{ device }} (Juniper)
      junipernetworks.junos.junos_l3_interfaces:
        config: 
          - name: "{{ interface }}"
            ipv6:
            - address: "{{ ip_address }}"
        state: merged
      become: true
      #when: address_family == '6' and hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: address_family == '6' and hostvars[inventory_hostname].tags.Name is match("^juniper-2$")

    - name: Update description to interface on {{ device }} (Juniper)
      junipernetworks.junos.junos_interfaces:
        config:
        - name: "{{ interface }}"
          description: "{{ description }}"
      become: true
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^juniper-2$")

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^juniper-2$")
    # - name: Rollback Juniper OS to last commit
    #   junipernetworks.junos.junos_config:
    #     rollback: 0
    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true
      #when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
      when: hostvars[inventory_hostname].tags.Name is match("^juniper-2$")
