---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Update Banner configs (Arista) 
  hosts: arista
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        data: "{{ ansible_eda.event.payload.data }}"

    - name: Debug Netbox data structure (Arista) 
      debug:
        msg: "{{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")

    - name: Debug Netbox relevant variables (Arista) 
      debug:
        msg: "{{ data.name }}, {{ data.data.login_banner }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")

    - name: Create Banner (Arista) 
      arista.eos.eos_banner:
        banner: login
        text: "{{ data.data.login_banner }}"
        state: present
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")


- name: Update Banner configs (Arista) 
  hosts: cisco
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        data: "{{ ansible_eda.event.payload.data }}"

    - name: Debug Netbox data structure (Cisco) 
      debug:
        msg: "{{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")

    - name: Debug Netbox relevant variables (Cisco) 
      debug:
        msg: "{{ data.name }}, {{ data.data.login_banner }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")

    - name: Create Banner (Cisco)
      cisco.ios.ios_banner:
        banner: login
        text: "{{ data.data.login_banner }}"
        state: present
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^cisco-2$")
