---

- name: Update interface vlan configs (Arista) 
  hosts: "{{ device }}"
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
  tasks:
    - name: Debug Netbox data structure
      debug:
        msg: "{{ data }}" 

    - name: Debug Netbox relevant variables
      debug:
        msg: "{{ device }}, {{ interface }}, {{ vlan_id }}, {{ vlan_name }}, {{ event }}, {{ timestamp }}, {{ data }}" 

    - name: Arista EOS update VLAN to {{ device }}
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ interface }}"
            mode: access
            access:
              vlan: "{{ vlan_id }}"
        state: merged
      become: true
