---


- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws

- name: Query data on Netbox
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files: vars/main.yml
  tasks:
    - name: Set Netbox URL
      set_fact:
        netbox_url: "http://{{ hostvars[groups['netbox'][0]].public_dns_name }}:8000"

    - name: Create a Token
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/users/tokens/provision/"
        method: POST
        body: |
          { 
            "username": "admin",
            "password": "{{ ec2_netbox_pass }}"
          }
        status_code: 201
        body_format: json
        headers:
          Content-Type: "application/json"
          Accept: "application/json; indent=4"
      run_once: true
      delegate_to: localhost
      register: netbox_token

    - name: Query VLANs on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'vlans',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query IPv4 addresses data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query interfaces data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query devices data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query device types data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'device-types',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query sites data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'sites',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Query sites data on Netbox
      debug:
        var: item
      loop: "{{ query('netbox.netbox.nb_lookup', 'config-context',
                    api_endpoint=netbox_url,
                    token=netbox_token.json.key,
                    validate_certs=False) }}"

    - name: Delete Token
      netbox.netbox.netbox_token:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token.json.key }}"
        data:
            key: "{{ netbox_token.json.key }}"
        state: absent
      run_once: true
      delegate_to: localhost