---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Update interface VLAN configs (Arista) 
  hosts: "{{ device }}"
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
  tasks:
    - name: Debug Netbox data structure (Arista) 
      debug:
        msg: "{{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")

    - name: Debug Netbox relevant variables (Arista) 
      debug:
        msg: "{{ device }}, {{ interface }}, {{ vlan_id }}, {{ vlan_name }}, {{ event }}, {{ timestamp }}, {{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")

    - name: Update VLAN to {{ device }} (Arista) 
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ interface }}"
            mode: access
            access:
              vlan: "{{ vlan_id }}"
        state: merged
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^arista-2$")


- name: Update interface VLAN configs (Juniper) 
  hosts: "{{ device }}"
  gather_facts: false
  vars_files: vars/main.yml
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_command_timeout: 300
  tasks:
    - name: Debug Netbox data structure (Juniper) 
      debug:
        msg: "{{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")

    - name: Debug Netbox relevant variables (Arista) 
      debug:
        msg: "{{ device }}, {{ interface }}, {{ vlan_id }}, {{ vlan_name }}, {{ event }}, {{ timestamp }}, {{ data }}" 
      when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")

    - name: Update VLAN to {{ device }} (Juniper) 
      junipernetworks.junos.junos_l2_interfaces:
        config:
          - name: "{{ interface }}"
            access:
              vlan: "{{ vlan_id }}"
        state: merged
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")

    - name: Check Juniper OS correctness of commit configuration
      junipernetworks.junos.junos_config:
        check_commit: true
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
    # - name: Rollback Juniper OS to last commit
    #   junipernetworks.junos.junos_config:
    #     rollback: 0
    - name: Confirm previous Juniper OS commit
      junipernetworks.junos.junos_config:
        confirm_commit: true
      become: true
      when: hostvars[inventory_hostname].tags.Name | regex_search("^juniper-2$")
