---

- name: Update interface vlan configs, triggered by Netbox changes
  hosts: "{{ device }}"
  gather_facts: false
  tasks:
    - include_vars: main.yml

    - name: Debug Netbox data structure
      debug:
        msg: "{{ data }}" 

    - name: Debug Netbox relevant variables
      debug:
        msg: "{{ device }}, {{ interface }}, {{ vlan_id }}, {{ vlan_name }}, {{ event }}, {{ timestamp }}, {{ data }}" 

    - name: Cisco IOS update VLAN to l2 interface on {{ device }}
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ interface }}"
            mode: access
            access:
              vlan: "{{ vlan_id }}"
        state: merged
      become: true

