---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (config events)"
  hosts: localhost
  # Source Netbox Webhook
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 6000
  # Rule config logs
  rules:
    - name: "Handle Branch Merge Event - Config"
      condition: event.payload.type == "CONFIG"
      actions:
        - print_event:
            pretty: true
        # Config tag compliance
        - run_job_template:
            organization: "Default"
            name: "AWS EDA Paloalto: Fix Compliance Tag"
        # Config log compliance
        - run_job_template:
            organization: "Default"
            name: "AWS EDA Paloalto: Fix Compliance Log"

