---
- name: "Receive Netbox Webhook events (config changes)"
  hosts: localhost

  # Source Netbox Webhook
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  # Rule config logs
  rules:

    - name: "Handle Config Context Change Event - Banner Config"
      condition: event.payload.data.name == "login_banner"
      actions:
        - print_event:
            pretty: true
        # Config banner
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: Update Config Context"

    - name: "Handle Config Context Change Event - DNS Config"
      condition: event.payload.data.name == "dns_servers"
      actions:
        - print_event:
            pretty: true
        # Config DNS
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: Update Config Context"
