---
- name: "Receive Netbox Webhook events (config changes)"
  hosts: localhost

  # Source Netbox Webhook
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  # Rule config logs
  rules:

    - name: "Handle Config Context Change Event - Banner Config"
      condition: event.payload.event == "job_ended" and event.payload.model == "branch" and event.payload.data.log is search("config context login_banner updated", ignorecase=true)
      actions:
        - print_event:
            pretty: true
        # Config banner
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: Update Config Context"

    - name: "Handle Config Context Change Event - DNS Config"
      condition: event.payload.event == "job_ended" and event.payload.model == "branch" and event.payload.data.log is search("DNS", ignorecase=true)
      actions:
        - print_event:
            pretty: true
        # Config DNS
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: Update Config Context"
