---
- name: "Receive Netbox Webhook events (config changes)"
  hosts: localhost

  # Source Netbox Webhook
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  # Rule config logs
  rules:

    - name: "Handle Branch Merge Event - Banner Config"
      condition: event.payload.type == "CONFIG"
      actions:
        - print_event:
            pretty: true
        # Config banner
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: Banner Config"

    - name: "Handle Branch Merge Event - DNS Config"
      condition: event.payload.event == "CONFIG"
      actions:
        - print_event:
            pretty: true
        # Config DNS
        - run_job_template:
            organization: "Default"
            name: "AWS Netbox: DNS Config"
