---

- name: Create VPC {{ ec2_vpc_name }}
  amazon.aws.ec2_vpc_net:
    name: "{{ ec2_vpc_name }}"
    cidr_block: "{{ ec2_vpc_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      name: "{{ ec2_vpc_name }}"
  register: vpc

- name: Create Subnet in VPC
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ ec2_subnet_cidr }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      name: "{{ ec2_subnet_name }}"
  register: subnet

- name: Create Internet Gateway (IGW)
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      name: "{{ ec2_igw_name }}"
  register: igw

- name: Create Route Table and IGW route
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ ec2_vpc_region }}"
    state: present
    tags:
      name: "{{ ec2_rt_name }}"
    subnets:
      - "{{ subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: Create Security Group
  amazon.aws.ec2_security_group:
    description: Allow all on ports
    name: "{{ ec2_sg_name }}"
    rules: "{{ ec2_sg_rules }}"
    region: "{{ ec2_vpc_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    state: present
    tags:
      name: "{{ ec2_sg_name }}"

# - name: check if ec2_key_pair is a file
#   stat:
#     path: "{{ ec2_key_pair }}"
#   register: ec2_key_pair_stat
#   when: ec2_key_pair is defined

# - name: import SSH Key from file
#   amazon.aws.ec2_key:
#     name: "{{ ec2_vpc_name }}"
#     key_material: "{{ lookup('file', ec2_key_pair ) }}"
#     region: "{{ ec2_region }}"
#   when:
#     - ec2_key_pair is defined
#     - ec2_key_pair_stat.stat.exists | bool

# - name: import SSH Key from variable
#   amazon.aws.ec2_key:
#     name: "{{ ec2_vpc_name }}"
#     key_material: "{{ ec2_key_pair }}"
#     region: "{{ ec2_region }}"
#   when:
#     - ec2_key_pair is defined
#     - not ec2_key_pair_stat.stat.exists | bool

- name: Get AMI by Name
  amazon.aws.ec2_ami_info:
    filters:
      name: "{{ ec2_netbox_image_name }}"
    region: "{{ ec2_vpc_region }}"
  register: ami_find

- name: Create Netbox instance
  amazon.aws.ec2_instance:
    image_id: "{{ ami_find.images[-1].image_id | default('') }}"
    instance_type: "{{ ec2_netbox_flavor_name }}"
    security_group: "{{ ec2_sg_name }}"
    name: "{{ ec2_netbox_instance_name }}"
    key_name: "{{ ec2_netbox_key_name }}"
    region: "{{ ec2_vpc_region }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    # network:
    #   assign_public_ip: true
    network_interfaces:
      - assign_public_ip: true
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: gp2
          volume_size: 32
          delete_on_termination: true
          encrypted: false
    tags:
      name: "{{ ec2_netbox_instance_name }}"
    state: running
  register: ec2_instance

- name: Print instance details
  ansible.builtin.debug:
    msg: "Netbox: http://{{ ec2_instance.instances[0].public_dns_name }}:8000 or http://{{ ec2_instance.instances[0].public_ip_address }}:8000"

- name: Sleep for 30 seconds and continue with play
  wait_for:
    timeout: 30
  delegate_to: localhost