# VPC NETBOX
ec2_vpc_name: VPC_NETBOX
ec2_vpc_region: us-east-1
ec2_vpc_cidr: 10.0.0.0/16
# AZ
ec2_vpc_availability_zone: us-east-1a
# Subnet
ec2_subnet_name: Subnet_NETBOX
ec2_subnet_cidr: 10.0.0.0/24
# IGW
ec2_igw_name: IGW_NETBOX
# Route Table
ec2_rt_name: RT_NETBOX
# RHEL Rules
ec2_sg_name: SG_NETBOX
ec2_sg_rules:
  - proto: tcp
    ports:
      - 80
      - 443
      - 22
      - 8000
    cidr_ip: 0.0.0.0/0
    rule_desc: Allow all on ports
  - proto: icmp
    icmp_code: -1 # icmp type, -1 = any type
    icmp_type:  -1 # icmp subtype, -1 = any subtype
    cidr_ip: 0.0.0.0/0
    rule_desc: Allow all ICMP

# NETBOX
# AMI
ec2_netbox_image_name: "Arara Solutions - Ubuntu 22.04 - NetBox community - v0224-prod-jz3khonabosm6"
ec2_netbox_image_id: ami-0d0dff5040aeeaf7f
# Volumes
ec2_netbox_volumes:
  - device_name: /dev/sda1
    ebs:
      volume_type: gp2
      volume_size: 32
      delete_on_termination: true
      encrypted: false
# Flavour 
ec2_netbox_flavor_name: t3.large
# Key Pair
ec2_netbox_key_name: "KeyPair-Virginia"
# Instance
ec2_netbox_instance_name: netbox-1

ec2_netbox_user: "{{ ansible_user }}"
ec2_netbox_pass: "{{ ansible_password }}"

# CISCO
# https://www.cisco.com/c/en/us/td/docs/routers/C8000V/AWS/deploying-c8000v-on-amazon-web-services/deploy-c8000v-on-amazon-web-services.html
# AMI
ec2_cisco_image_name: "Cisco-C8K-PAYG-ESS-17.15.02a-0973be0f-17dc-43c1-9677-13348bbfe587"
ec2_cisco_image_id: ami-070b9ff0a5ff52017
# Volumes
ec2_cisco_volumes:
  - device_name: /dev/xvda
    ebs:
      volume_type: gp2
      volume_size: 16
      delete_on_termination: true
      encrypted: false
# Flavour 
#ec2_netbox_flavor_name: t3.medium
ec2_cisco_flavor_name: c5.large
# Key Pair
ec2_cisco_key_name: "KeyPair-Virginia"
# Instance
ec2_cisco_instance_name: cisco-1

# ec2-user / ?
ec2_cisco_user: "{{ ansible_user }}"
ec2_cisco_pass: "{{ ansible_password }}"

# ARISTA
# AMI
ec2_arista_image_name: "CloudEOS4.32.2F-971505ec-86ee-48a7-a33b-54295288e797"
ec2_arista_image_id: ami-0f3d624fef6d9acf3
# Volumes
ec2_arista_volumes:
  - device_name: /dev/xvda
    ebs:
      volume_type: gp2
      volume_size: 8
      delete_on_termination: true
      encrypted: false
# Flavour 
ec2_arista_flavor_name: c5.xlarge
# Key Pair
ec2_arista_key_name: "KeyPair-Virginia"
# Instance
ec2_arista_instance_name: arista-1

# ec2-user / ?
ec2_arista_user: "{{ ansible_user }}"
ec2_arista_pass: "{{ ansible_password }}"